version: "3.8"

services:
  web:
    image: ${DOCKER_HUB_USERNAME}/random_user_generator-web:latest
    ports:
      - "5000:5000"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - webnet

networks:
  webnet:
