version: "3.0"
services:
  web:
    image: ${{secrets.DOCKER_HUB.USERNAME}}/random-user-generator:v1
    ports:
      - "5000:5000"
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

    networks:
      - webnet
networks:
  webnet:

